name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/devops-gruppe-2/search-engine:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull ghcr.io/devops-gruppe-2/search-engine:latest

            docker stop whoknows-backend || true
            docker rm whoknows-backend || true

            docker run -d \
              --name whoknows-backend \
              --restart unless-stopped \
              -p 8080:8080 \
              -v /home/azureuser/app.db:/app/app.db \
              ghcr.io/devops-gruppe-2/search-engine:latest