name: CI

on:
  push:
    branches:
      - main
      - feature/ci-cd

  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Download dependencies
        working-directory: backend
        run: go mod download

      - name: Run tests
        working-directory: backend
        run: go test ./...

      - name: Build backend
        working-directory: backend
        run: go build -o backend main.go

      - name: Build Docker image
        working-directory: backend
        run: docker build -t whoknows-backend .